// export const SIGN_IN = 'SIGN_IN';
// export const SIGN_OUT = 'SIGN_OUT';

// export const FETCH_USER = 'FETCH_USER';


export const LOG_IN_SUCESS = 'LOG_IN_SUCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';
export const LOG_OUT = 'LOG_OUT';

export const FETCH_USER_ID = 'FETCH_USER_ID';
export const FETCH_USER_ID_SUCCESS = 'FETCH_USER_ID_SUCCESS';
export const FETCH_USER_ID_FAILURE = 'FETCH_USER_ID_FAILURE';

export const REORDER_TRACK = 'REORDER_TRACK';
export const REORDER_TRACK_SUCCESS = 'REORDER_TRACK_SUCCESS';
export const REORDER_TRACK_FAILURE = 'REORDER_TRACK_FAILURE';


export const FETCH_PLAYLISTS = 'FETCH_PLAYLISTS';

export const FETCH_PLAYLIST = 'FETCH_PLAYLIST';
export const FETCH_PLAYLIST_SUCCESS = 'FETCH_PLAYLIST_SUCCESS';
export const FETCH_PLAYLIST_FAILURE = 'FETCH_PLAYLIST_FAILURE';


export const INCREASE_VOTE = 'INCREASE_VOTE';
export const DECREASE_VOTE = 'DECREASE_VOTE';
export const MOVE_UP_PlAYLIST = 'MOVE_UP_PlAYLIST';
export const MOVE_DOWN_PlAYLIST = 'MOVE_DOWN_PlAYLIST';
export const REMOVE_FROM_PLAYLIST = 'REMOVE_FROM_PLAYLIST';

export const REMOVE_TRACK = 'REMOVE_TRACK';
export const REMOVE_TRACK_SUCCESS = 'REMOVE_TRACK_SUCCESS';
export const REMOVE_TRACK_FAILURE = 'REMOVE_TRACK_FAILURE';


export const FETCH_SEARCH_RESULTS = 'FETCH_SEARCH_RESULTS';
export const FETCH_SEARCH_RESULTS_SUCCESS = 'FETCH_SEARCH_RESULTS_SUCCESS';
export const FETCH_SEARCH_RESULTS_FAILURE = 'FETCH_SEARCH_RESULTS_FAILURE';

export const RESUME_PLAYBACK = 'RESUME_PLAYBACK';
export const RESUME_PLAYBACK_SUCCESS = 'RESUME_PLAYBACK_SUCCESS';
export const RESUME_PLAYBACK_FAILURE = 'RESUME_PLAYBACK_FAILURE';

export const PAUSE_PLAYBACK = 'PAUSE_PLAYBACK';
export const PAUSE_PLAYBACK_SUCCESS = 'PAUSE_PLAYBACK_SUCCESS';
export const PAUSE_PLAYBACK_FAILURE = 'PAUSE_PLAYBACK_FAILURE';

export const GET_CURRENTLY_PLAYING = 'GET_CURRENTLY_PLAYING';
export const GET_CURRENTLY_PLAYING_SUCCESS = 'GET_CURRENTLY_PLAYING_SUCCESS';
export const GET_CURRENTLY_PLAYING_FAILURE = 'GET_CURRENTLY_PLAYING_FAILURE';

export const START_SESSION = 'START_SESSION';

export const SET_RECENTLY_CLICKED = 'SET_RECENTLY_CLICKED';
