// auth
export const LOG_IN_SUCESS = 'LOG_IN_SUCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';
export const LOG_OUT = 'LOG_OUT';

// user
export const FETCH_USER_ID = 'FETCH_USER_ID';
export const FETCH_USER_ID_SUCCESS = 'FETCH_USER_ID_SUCCESS';
export const FETCH_USER_ID_FAILURE = 'FETCH_USER_ID_FAILURE';

// search
export const FETCH_SEARCH_RESULTS = 'FETCH_SEARCH_RESULTS';
export const FETCH_SEARCH_RESULTS_SUCCESS = 'FETCH_SEARCH_RESULTS_SUCCESS';
export const FETCH_SEARCH_RESULTS_FAILURE = 'FETCH_SEARCH_RESULTS_FAILURE';
export const CLEAR_RESULTS = 'CLEAR_RESULTS';

// playlist fetch
export const FETCH_PLAYLIST_FROM_DB = 'FETCH_PLAYLIST_FROM_DB';
export const FETCH_PLAYLIST_FROM_DB_SUCCESS = 'FETCH_PLAYLIST_FROM_DB_SUCCESS';
export const FETCH_PLAYLIST_FROM_DB_FAILURE = 'FETCH_PLAYLIST_FROM_DB_FAILURE';

// playlist
export const UPDATE_TRACK = 'UPDATE_TRACK'
export const UPDATE_TRACK_SUCCESS = 'UPDATE_TRACK_SUCCESS'
export const UPDATE_TRACK_FAILURE = 'UPDATE_TRACK_FAILURE'

export const ADD_TO_PLAYLIST = 'ADD_TO_PLAYLIST';
export const ADD_TO_PLAYLIST_SUCCESS = 'ADD_TO_PLAYLIST_SUCCESS';
export const ADD_TO_PLAYLIST_FAILURE = 'ADD_TO_PLAYLIST_FAILURE';
export const ADD_TO_PLAYLIST_DISALLOWED = 'ADD_TO_PLAYLIST_DISALLOWED';

export const DELETE_TRACK = 'DELETE_TRACK';
export const DELETE_TRACK_SUCCESS = 'DELETE_TRACK_SUCCESS';
export const DELETE_TRACK_FAILURE = 'DELETE_TRACK_FAILURE';

export const UPVOTE_LIMIT_EXCEEDED = 'UPVOTE_LIMIT_EXCEEDED';
export const DOWNVOTE_LIMIT_EXCEEDED = 'DOWNVOTE_LIMIT_EXCEEDED';

// playback
export const UPDATE_CURRENT_TRACK = 'UPDATE_CURRENT_TRACK';
export const UPDATE_CURRENT_TRACK_SUCCESS = 'UPDATE_CURRENT_TRACK_SUCCESS';
export const UPDATE_CURRENT_TRACK_FAILURE = 'UPDATE_CURRENT_TRACK_FAILURE';

export const GET_CURRENTLY_PLAYING = 'GET_CURRENTLY_PLAYING';
export const GET_CURRENTLY_PLAYING_SUCCESS = 'GET_CURRENTLY_PLAYING_SUCCESS';
export const GET_CURRENTLY_PLAYING_FAILURE = 'GET_CURRENTLY_PLAYING_FAILURE';

export const RESUME_PLAYBACK = 'RESUME_PLAYBACK';
export const RESUME_PLAYBACK_SUCCESS = 'RESUME_PLAYBACK_SUCCESS';
export const RESUME_PLAYBACK_FAILURE = 'RESUME_PLAYBACK_FAILURE';

export const PAUSE_PLAYBACK = 'PAUSE_PLAYBACK';
export const PAUSE_PLAYBACK_SUCCESS = 'PAUSE_PLAYBACK_SUCCESS';
export const PAUSE_PLAYBACK_FAILURE = 'PAUSE_PLAYBACK_FAILURE';

export const socketTypes = [
  UPDATE_TRACK_SUCCESS,
  ADD_TO_PLAYLIST_SUCCESS,
  RESUME_PLAYBACK_SUCCESS,
  PAUSE_PLAYBACK_SUCCESS,
  DELETE_TRACK_SUCCESS,
  UPDATE_CURRENT_TRACK_SUCCESS
];

